//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrippLite.Globalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrippLite.Globalization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        internal static string Abort {
            get {
                return ResourceManager.GetString("Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A/C Power.
        /// </summary>
        internal static string ACPower {
            get {
                return ResourceManager.GetString("ACPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm.
        /// </summary>
        internal static string Alarm {
            get {
                return ResourceManager.GetString("Alarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        internal static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amp.
        /// </summary>
        internal static string Amp {
            get {
                return ResourceManager.GetString("Amp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amperage.
        /// </summary>
        internal static string Amperage {
            get {
                return ResourceManager.GetString("Amperage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amps.
        /// </summary>
        internal static string Amps {
            get {
                return ResourceManager.GetString("Amps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BatteryMon.
        /// </summary>
        internal static string AppShortTitle {
            get {
                return ResourceManager.GetString("AppShortTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery Device Monitor.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Properties.
        /// </summary>
        internal static string AvailableProperties {
            get {
                return ResourceManager.GetString("AvailableProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Color.
        /// </summary>
        internal static string BackColor {
            get {
                return ResourceManager.GetString("BackColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Settings.
        /// </summary>
        internal static string BackgroundSettings {
            get {
                return ResourceManager.GetString("BackgroundSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery Device.
        /// </summary>
        internal static string BatteryDevice {
            get {
                return ResourceManager.GetString("BatteryDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery Devices.
        /// </summary>
        internal static string BatteryDevices {
            get {
                return ResourceManager.GetString("BatteryDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery Power.
        /// </summary>
        internal static string BatteryPower {
            get {
                return ResourceManager.GetString("BatteryPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blackout.
        /// </summary>
        internal static string Blackout {
            get {
                return ResourceManager.GetString("Blackout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold.
        /// </summary>
        internal static string Bold {
            get {
                return ResourceManager.GetString("Bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brown Out.
        /// </summary>
        internal static string BrownOut {
            get {
                return ResourceManager.GetString("BrownOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celsius.
        /// </summary>
        internal static string Celsius {
            get {
                return ResourceManager.GetString("Celsius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge.
        /// </summary>
        internal static string Charge {
            get {
                return ResourceManager.GetString("Charge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge Remaining.
        /// </summary>
        internal static string ChargeRemaining {
            get {
                return ResourceManager.GetString("ChargeRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charging.
        /// </summary>
        internal static string Charging {
            get {
                return ResourceManager.GetString("Charging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Power System.
        /// </summary>
        internal static string ChoosePowerSystem {
            get {
                return ResourceManager.GetString("ChoosePowerSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Power Systems.
        /// </summary>
        internal static string ChoosePowerSystems {
            get {
                return ResourceManager.GetString("ChoosePowerSystems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press and hold here to drag and move the window..
        /// </summary>
        internal static string ClickDragMove {
            get {
                return ResourceManager.GetString("ClickDragMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection Type.
        /// </summary>
        internal static string CollectionType {
            get {
                return ResourceManager.GetString("CollectionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        internal static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cool Window Colors.
        /// </summary>
        internal static string CoolWindowColors {
            get {
                return ResourceManager.GetString("CoolWindowColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New ....
        /// </summary>
        internal static string CreateNew {
            get {
                return ResourceManager.GetString("CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application has encountered a critical failure and will now terminate..
        /// </summary>
        internal static string CriticalFailQuitMessage {
            get {
                return ResourceManager.GetString("CriticalFailQuitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical Failure.
        /// </summary>
        internal static string CriticalFailure {
            get {
                return ResourceManager.GetString("CriticalFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Power System Status.
        /// </summary>
        internal static string CurrentPowerSystemStatus {
            get {
                return ResourceManager.GetString("CurrentPowerSystemStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        internal static string Device {
            get {
                return ResourceManager.GetString("Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices.
        /// </summary>
        internal static string Devices {
            get {
                return ResourceManager.GetString("Devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discharging.
        /// </summary>
        internal static string Discharging {
            get {
                return ResourceManager.GetString("Discharging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamic Properties.
        /// </summary>
        internal static string DynamicProperties {
            get {
                return ResourceManager.GetString("DynamicProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fahrenheit.
        /// </summary>
        internal static string Fahrenheit {
            get {
                return ResourceManager.GetString("Fahrenheit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        internal static string Font {
            get {
                return ResourceManager.GetString("Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Family.
        /// </summary>
        internal static string FontFamily {
            get {
                return ResourceManager.GetString("FontFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Size.
        /// </summary>
        internal static string FontSize {
            get {
                return ResourceManager.GetString("FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreground Color.
        /// </summary>
        internal static string ForeColor {
            get {
                return ResourceManager.GetString("ForeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreground Settings.
        /// </summary>
        internal static string ForegroundSettings {
            get {
                return ResourceManager.GetString("ForegroundSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/nmoschkin/BatteryMon.
        /// </summary>
        internal static string GitHubLink {
            get {
                return ResourceManager.GetString("GitHubLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have a bug to report, or any other issue, please reach out to me via the GitHub repository page..
        /// </summary>
        internal static string HaveIssuesText {
            get {
                return ResourceManager.GetString("HaveIssuesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hertz.
        /// </summary>
        internal static string Hertz {
            get {
                return ResourceManager.GetString("Hertz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HID.
        /// </summary>
        internal static string HID {
            get {
                return ResourceManager.GetString("HID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Human Interface Device.
        /// </summary>
        internal static string HID_Long {
            get {
                return ResourceManager.GetString("HID_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HID Usage Page.
        /// </summary>
        internal static string HIDUsagePage {
            get {
                return ResourceManager.GetString("HIDUsagePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HID Usage Pages.
        /// </summary>
        internal static string HIDUsagePages {
            get {
                return ResourceManager.GetString("HIDUsagePages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italic.
        /// </summary>
        internal static string Italic {
            get {
                return ResourceManager.GetString("Italic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kelvin.
        /// </summary>
        internal static string Kelvin {
            get {
                return ResourceManager.GetString("Kelvin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Side Meter.
        /// </summary>
        internal static string LeftMeter {
            get {
                return ResourceManager.GetString("LeftMeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Side Property.
        /// </summary>
        internal static string LeftSideProperty {
            get {
                return ResourceManager.GetString("LeftSideProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        internal static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mains Status.
        /// </summary>
        internal static string MainsStatus {
            get {
                return ResourceManager.GetString("MainsStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Primary.
        /// </summary>
        internal static string NotPrimary {
            get {
                return ResourceManager.GetString("NotPrimary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opacity.
        /// </summary>
        internal static string Opacity {
            get {
                return ResourceManager.GetString("Opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Cool Window.
        /// </summary>
        internal static string OpenCoolWindow {
            get {
                return ResourceManager.GetString("OpenCoolWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Desktop Window.
        /// </summary>
        internal static string OpenMainWindow {
            get {
                return ResourceManager.GetString("OpenMainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open System Power Settings.
        /// </summary>
        internal static string OpenSystemPowerSettings {
            get {
                return ResourceManager.GetString("OpenSystemPowerSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percent Remaining.
        /// </summary>
        internal static string PercentRemaining {
            get {
                return ResourceManager.GetString("PercentRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Device.
        /// </summary>
        internal static string PowerDevice {
            get {
                return ResourceManager.GetString("PowerDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Devices.
        /// </summary>
        internal static string PowerDevices {
            get {
                return ResourceManager.GetString("PowerDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power System Failure.
        /// </summary>
        internal static string PowerSystemFailure {
            get {
                return ResourceManager.GetString("PowerSystemFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary.
        /// </summary>
        internal static string Primary {
            get {
                return ResourceManager.GetString("Primary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReportBugs.
        /// </summary>
        internal static string ReportBugs {
            get {
                return ResourceManager.GetString("ReportBugs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        internal static string Retry {
            get {
                return ResourceManager.GetString("Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Right Property.
        /// </summary>
        internal static string RightPropertyBottom {
            get {
                return ResourceManager.GetString("RightPropertyBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upper Right Property.
        /// </summary>
        internal static string RightPropertyTop {
            get {
                return ResourceManager.GetString("RightPropertyTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run On Startup.
        /// </summary>
        internal static string RunOnLogin {
            get {
                return ResourceManager.GetString("RunOnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As ....
        /// </summary>
        internal static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Alarm Mode.
        /// </summary>
        internal static string SelectAlarmMode {
            get {
                return ResourceManager.GetString("SelectAlarmMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select one or more power devices from the list..
        /// </summary>
        internal static string SelectBatteries_Long {
            get {
                return ResourceManager.GetString("SelectBatteries_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a power device from the list..
        /// </summary>
        internal static string SelectBattery_Long {
            get {
                return ResourceManager.GetString("SelectBattery_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Multiple.
        /// </summary>
        internal static string SelectMany {
            get {
                return ResourceManager.GetString("SelectMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Only One.
        /// </summary>
        internal static string SelectOne {
            get {
                return ResourceManager.GetString("SelectOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor.
        /// </summary>
        internal static string Sensor {
            get {
                return ResourceManager.GetString("Sensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor Data.
        /// </summary>
        internal static string SensorData {
            get {
                return ResourceManager.GetString("SensorData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor Readings.
        /// </summary>
        internal static string SensorReadings {
            get {
                return ResourceManager.GetString("SensorReadings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensors.
        /// </summary>
        internal static string Sensors {
            get {
                return ResourceManager.GetString("Sensors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set As Default.
        /// </summary>
        internal static string SetDefault {
            get {
                return ResourceManager.GetString("SetDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Power Devices.
        /// </summary>
        internal static string ShowPowerDevices {
            get {
                return ResourceManager.GetString("ShowPowerDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutdown.
        /// </summary>
        internal static string Shutdown {
            get {
                return ResourceManager.GetString("Shutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surge.
        /// </summary>
        internal static string Surge {
            get {
                return ResourceManager.GetString("Surge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        internal static string Temperature {
            get {
                return ResourceManager.GetString("Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        internal static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Completed and Failed.
        /// </summary>
        internal static string TestCompletedFailed {
            get {
                return ResourceManager.GetString("TestCompletedFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Completed and Passed.
        /// </summary>
        internal static string TestCompletedPassed {
            get {
                return ResourceManager.GetString("TestCompletedPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing.
        /// </summary>
        internal static string Testing {
            get {
                return ResourceManager.GetString("Testing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Color.
        /// </summary>
        internal static string TextColor {
            get {
                return ResourceManager.GetString("TextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Settings.
        /// </summary>
        internal static string TextSettings {
            get {
                return ResourceManager.GetString("TextSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Remaining.
        /// </summary>
        internal static string TimeRemaining {
            get {
                return ResourceManager.GetString("TimeRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPS.
        /// </summary>
        internal static string UPS {
            get {
                return ResourceManager.GetString("UPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninterruptable Power Supply.
        /// </summary>
        internal static string UPS_Long {
            get {
                return ResourceManager.GetString("UPS_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volt.
        /// </summary>
        internal static string Volt {
            get {
                return ResourceManager.GetString("Volt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltage.
        /// </summary>
        internal static string Voltage {
            get {
                return ResourceManager.GetString("Voltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volts.
        /// </summary>
        internal static string Volts {
            get {
                return ResourceManager.GetString("Volts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watt.
        /// </summary>
        internal static string Watt {
            get {
                return ResourceManager.GetString("Watt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watts.
        /// </summary>
        internal static string Watts {
            get {
                return ResourceManager.GetString("Watts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Devices.
        /// </summary>
        internal static string XDevices {
            get {
                return ResourceManager.GetString("XDevices", resourceCulture);
            }
        }
    }
}
