// ------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// Runtime Version:4.0.30319.42000
// 
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Diagnostics;

using Microsoft.VisualBasic;

namespace TrippLite.My.Resources
{

    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [DebuggerNonUserCode()]
    [System.Runtime.CompilerServices.CompilerGenerated()]
    [HideModuleName()]
    internal static class Resources
    {
        private static System.Resources.ResourceManager resourceMan;
        private static System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(resourceMan, null))
                {
                    var temp = new System.Resources.ResourceManager("TrippLite.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }

                return resourceMan;
            }
        }

        /// <summary>
        /// Overrides the current thread's CurrentUICulture property for all
        /// resource lookups using this strongly typed resource class.
        /// </summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }

            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cmdleft
        {
            get
            {
                var obj = ResourceManager.GetObject("cmdleft", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cmdleftb
        {
            get
            {
                var obj = ResourceManager.GetObject("cmdleftb", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cmdright
        {
            get
            {
                var obj = ResourceManager.GetObject("cmdright", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cmdrightb
        {
            get
            {
                var obj = ResourceManager.GetObject("cmdrightb", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DIGITALDREAMSKEWNARROW
        {
            get
            {
                var obj = ResourceManager.GetObject("DIGITALDREAMSKEWNARROW", resourceCulture);
                return (byte[])obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TrippLiteLogo
        {
            get
            {
                var obj = ResourceManager.GetObject("TrippLiteLogo", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TrippLiteSmart1500LCDT
        {
            get
            {
                var obj = ResourceManager.GetObject("TrippLiteSmart1500LCDT", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }
    }
}